// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zerpto/ponodo/contracts (interfaces: AppContract)
//
// Generated by this command:
//
//	Cursor.AppImage -package=mocks github.com/zerpto/ponodo/contracts AppContract
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	validator "github.com/go-playground/validator/v10"
	contracts "github.com/zerpto/ponodo/cli/contracts"
	config "github.com/zerpto/ponodo/config"
	contracts0 "github.com/zerpto/ponodo/contracts"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockAppContract is a mock of AppContract interface.
type MockAppContract struct {
	ctrl     *gomock.Controller
	recorder *MockAppContractMockRecorder
	isgomock struct{}
}

// MockAppContractMockRecorder is the mock recorder for MockAppContract.
type MockAppContractMockRecorder struct {
	mock *MockAppContract
}

// NewMockAppContract creates a new mock instance.
func NewMockAppContract(ctrl *gomock.Controller) *MockAppContract {
	mock := &MockAppContract{ctrl: ctrl}
	mock.recorder = &MockAppContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppContract) EXPECT() *MockAppContractMockRecorder {
	return m.recorder
}

// AddCommand mocks base method.
func (m *MockAppContract) AddCommand(arg0 func(contracts0.AppContract) contracts.CommandContract) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddCommand", arg0)
}

// AddCommand indicates an expected call of AddCommand.
func (mr *MockAppContractMockRecorder) AddCommand(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommand", reflect.TypeOf((*MockAppContract)(nil).AddCommand), arg0)
}

// GetConfigLoader mocks base method.
func (m *MockAppContract) GetConfigLoader() *config.Loader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfigLoader")
	ret0, _ := ret[0].(*config.Loader)
	return ret0
}

// GetConfigLoader indicates an expected call of GetConfigLoader.
func (mr *MockAppContractMockRecorder) GetConfigLoader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfigLoader", reflect.TypeOf((*MockAppContract)(nil).GetConfigLoader))
}

// GetDb mocks base method.
func (m *MockAppContract) GetDb() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDb")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// GetDb indicates an expected call of GetDb.
func (mr *MockAppContractMockRecorder) GetDb() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDb", reflect.TypeOf((*MockAppContract)(nil).GetDb))
}

// GetGin mocks base method.
func (m *MockAppContract) GetGin() *gin.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGin")
	ret0, _ := ret[0].(*gin.Engine)
	return ret0
}

// GetGin indicates an expected call of GetGin.
func (mr *MockAppContractMockRecorder) GetGin() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGin", reflect.TypeOf((*MockAppContract)(nil).GetGin))
}

// GetValidator mocks base method.
func (m *MockAppContract) GetValidator() *validator.Validate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidator")
	ret0, _ := ret[0].(*validator.Validate)
	return ret0
}

// GetValidator indicates an expected call of GetValidator.
func (mr *MockAppContractMockRecorder) GetValidator() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidator", reflect.TypeOf((*MockAppContract)(nil).GetValidator))
}

// Run mocks base method.
func (m *MockAppContract) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockAppContractMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockAppContract)(nil).Run))
}

// SetConfigLoader mocks base method.
func (m *MockAppContract) SetConfigLoader(arg0 *config.Loader) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConfigLoader", arg0)
}

// SetConfigLoader indicates an expected call of SetConfigLoader.
func (mr *MockAppContractMockRecorder) SetConfigLoader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConfigLoader", reflect.TypeOf((*MockAppContract)(nil).SetConfigLoader), arg0)
}

// SetGin mocks base method.
func (m *MockAppContract) SetGin(arg0 *gin.Engine) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGin", arg0)
}

// SetGin indicates an expected call of SetGin.
func (mr *MockAppContractMockRecorder) SetGin(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGin", reflect.TypeOf((*MockAppContract)(nil).SetGin), arg0)
}

// SetValidator mocks base method.
func (m *MockAppContract) SetValidator(arg0 *validator.Validate) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetValidator", arg0)
}

// SetValidator indicates an expected call of SetValidator.
func (mr *MockAppContractMockRecorder) SetValidator(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetValidator", reflect.TypeOf((*MockAppContract)(nil).SetValidator), arg0)
}

// SetupBaseDependencies mocks base method.
func (m *MockAppContract) SetupBaseDependencies() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetupBaseDependencies")
}

// SetupBaseDependencies indicates an expected call of SetupBaseDependencies.
func (mr *MockAppContractMockRecorder) SetupBaseDependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupBaseDependencies", reflect.TypeOf((*MockAppContract)(nil).SetupBaseDependencies))
}
