// Code generated by MockGen. DO NOT EDIT.
// Source: config/contracts/config_contract.go
//
// Generated by this command:
//
//	Cursor.AppImage -source=config/contracts/config_contract.go -destination=mocks/mock_config_contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contracts "github.com/zerpto/ponodo/config/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockDbConfigContract is a mock of DbConfigContract interface.
type MockDbConfigContract struct {
	ctrl     *gomock.Controller
	recorder *MockDbConfigContractMockRecorder
	isgomock struct{}
}

// MockDbConfigContractMockRecorder is the mock recorder for MockDbConfigContract.
type MockDbConfigContractMockRecorder struct {
	mock *MockDbConfigContract
}

// NewMockDbConfigContract creates a new mock instance.
func NewMockDbConfigContract(ctrl *gomock.Controller) *MockDbConfigContract {
	mock := &MockDbConfigContract{ctrl: ctrl}
	mock.recorder = &MockDbConfigContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbConfigContract) EXPECT() *MockDbConfigContractMockRecorder {
	return m.recorder
}

// GetDatabase mocks base method.
func (m *MockDbConfigContract) GetDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockDbConfigContractMockRecorder) GetDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockDbConfigContract)(nil).GetDatabase))
}

// GetHost mocks base method.
func (m *MockDbConfigContract) GetHost() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHost indicates an expected call of GetHost.
func (mr *MockDbConfigContractMockRecorder) GetHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockDbConfigContract)(nil).GetHost))
}

// GetPassword mocks base method.
func (m *MockDbConfigContract) GetPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockDbConfigContractMockRecorder) GetPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockDbConfigContract)(nil).GetPassword))
}

// GetPort mocks base method.
func (m *MockDbConfigContract) GetPort() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPort")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPort indicates an expected call of GetPort.
func (mr *MockDbConfigContractMockRecorder) GetPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPort", reflect.TypeOf((*MockDbConfigContract)(nil).GetPort))
}

// GetUser mocks base method.
func (m *MockDbConfigContract) GetUser() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUser indicates an expected call of GetUser.
func (mr *MockDbConfigContractMockRecorder) GetUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDbConfigContract)(nil).GetUser))
}

// MockConfigContract is a mock of ConfigContract interface.
type MockConfigContract struct {
	ctrl     *gomock.Controller
	recorder *MockConfigContractMockRecorder
	isgomock struct{}
}

// MockConfigContractMockRecorder is the mock recorder for MockConfigContract.
type MockConfigContractMockRecorder struct {
	mock *MockConfigContract
}

// NewMockConfigContract creates a new mock instance.
func NewMockConfigContract(ctrl *gomock.Controller) *MockConfigContract {
	mock := &MockConfigContract{ctrl: ctrl}
	mock.recorder = &MockConfigContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigContract) EXPECT() *MockConfigContractMockRecorder {
	return m.recorder
}

// GetApp mocks base method.
func (m *MockConfigContract) GetApp() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApp indicates an expected call of GetApp.
func (mr *MockConfigContractMockRecorder) GetApp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockConfigContract)(nil).GetApp))
}

// GetDb mocks base method.
func (m *MockConfigContract) GetDb() contracts.DbConfigContract {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDb")
	ret0, _ := ret[0].(contracts.DbConfigContract)
	return ret0
}

// GetDb indicates an expected call of GetDb.
func (mr *MockConfigContractMockRecorder) GetDb() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDb", reflect.TypeOf((*MockConfigContract)(nil).GetDb))
}

// GetDebug mocks base method.
func (m *MockConfigContract) GetDebug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetDebug indicates an expected call of GetDebug.
func (mr *MockConfigContractMockRecorder) GetDebug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebug", reflect.TypeOf((*MockConfigContract)(nil).GetDebug))
}

// GetEnv mocks base method.
func (m *MockConfigContract) GetEnv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnv")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEnv indicates an expected call of GetEnv.
func (mr *MockConfigContractMockRecorder) GetEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnv", reflect.TypeOf((*MockConfigContract)(nil).GetEnv))
}
