// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zerpto/ponodo/cli/contracts (interfaces: CommandContract)
//
// Generated by this command:
//
//	Cursor.AppImage -package=mocks github.com/zerpto/ponodo/cli/contracts CommandContract
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cobra "github.com/spf13/cobra"
	gomock "go.uber.org/mock/gomock"
)

// MockCommandContract is a mock of CommandContract interface.
type MockCommandContract struct {
	ctrl     *gomock.Controller
	recorder *MockCommandContractMockRecorder
	isgomock struct{}
}

// MockCommandContractMockRecorder is the mock recorder for MockCommandContract.
type MockCommandContractMockRecorder struct {
	mock *MockCommandContract
}

// NewMockCommandContract creates a new mock instance.
func NewMockCommandContract(ctrl *gomock.Controller) *MockCommandContract {
	mock := &MockCommandContract{ctrl: ctrl}
	mock.recorder = &MockCommandContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandContract) EXPECT() *MockCommandContractMockRecorder {
	return m.recorder
}

// Example mocks base method.
func (m *MockCommandContract) Example() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Example")
	ret0, _ := ret[0].(string)
	return ret0
}

// Example indicates an expected call of Example.
func (mr *MockCommandContractMockRecorder) Example() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Example", reflect.TypeOf((*MockCommandContract)(nil).Example))
}

// Long mocks base method.
func (m *MockCommandContract) Long() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Long")
	ret0, _ := ret[0].(string)
	return ret0
}

// Long indicates an expected call of Long.
func (mr *MockCommandContractMockRecorder) Long() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Long", reflect.TypeOf((*MockCommandContract)(nil).Long))
}

// Run mocks base method.
func (m *MockCommandContract) Run(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", cmd, args)
}

// Run indicates an expected call of Run.
func (mr *MockCommandContractMockRecorder) Run(cmd, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommandContract)(nil).Run), cmd, args)
}

// Short mocks base method.
func (m *MockCommandContract) Short() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Short")
	ret0, _ := ret[0].(string)
	return ret0
}

// Short indicates an expected call of Short.
func (mr *MockCommandContractMockRecorder) Short() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Short", reflect.TypeOf((*MockCommandContract)(nil).Short))
}

// Use mocks base method.
func (m *MockCommandContract) Use() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use")
	ret0, _ := ret[0].(string)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockCommandContractMockRecorder) Use() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockCommandContract)(nil).Use))
}
