// Code generated by MockGen. DO NOT EDIT.
// Source: config_contract.go
//
// Generated by this command:
//
//	mockgen -source=config_contract.go -destination=./mocks/mock_config_contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	contracts "github.com/zerpto/ponodo/config/contracts"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigContract is a mock of ConfigContract interface.
type MockConfigContract struct {
	ctrl     *gomock.Controller
	recorder *MockConfigContractMockRecorder
	isgomock struct{}
}

// MockConfigContractMockRecorder is the mock recorder for MockConfigContract.
type MockConfigContractMockRecorder struct {
	mock *MockConfigContract
}

// NewMockConfigContract creates a new mock instance.
func NewMockConfigContract(ctrl *gomock.Controller) *MockConfigContract {
	mock := &MockConfigContract{ctrl: ctrl}
	mock.recorder = &MockConfigContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigContract) EXPECT() *MockConfigContractMockRecorder {
	return m.recorder
}

// GetApp mocks base method.
func (m *MockConfigContract) GetApp() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetApp indicates an expected call of GetApp.
func (mr *MockConfigContractMockRecorder) GetApp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockConfigContract)(nil).GetApp))
}

// GetDb mocks base method.
func (m *MockConfigContract) GetDb() contracts.DbConfigContract {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDb")
	ret0, _ := ret[0].(contracts.DbConfigContract)
	return ret0
}

// GetDb indicates an expected call of GetDb.
func (mr *MockConfigContractMockRecorder) GetDb() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDb", reflect.TypeOf((*MockConfigContract)(nil).GetDb))
}

// GetDebug mocks base method.
func (m *MockConfigContract) GetDebug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetDebug indicates an expected call of GetDebug.
func (mr *MockConfigContractMockRecorder) GetDebug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebug", reflect.TypeOf((*MockConfigContract)(nil).GetDebug))
}

// GetEnv mocks base method.
func (m *MockConfigContract) GetEnv() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnv")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetEnv indicates an expected call of GetEnv.
func (mr *MockConfigContractMockRecorder) GetEnv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnv", reflect.TypeOf((*MockConfigContract)(nil).GetEnv))
}
