// Code generated by MockGen. DO NOT EDIT.
// Source: db_contract.go
//
// Generated by this command:
//
//	mockgen -source=db_contract.go -destination=./mocks/mock_db_contract.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDbConfigContract is a mock of DbConfigContract interface.
type MockDbConfigContract struct {
	ctrl     *gomock.Controller
	recorder *MockDbConfigContractMockRecorder
	isgomock struct{}
}

// MockDbConfigContractMockRecorder is the mock recorder for MockDbConfigContract.
type MockDbConfigContractMockRecorder struct {
	mock *MockDbConfigContract
}

// NewMockDbConfigContract creates a new mock instance.
func NewMockDbConfigContract(ctrl *gomock.Controller) *MockDbConfigContract {
	mock := &MockDbConfigContract{ctrl: ctrl}
	mock.recorder = &MockDbConfigContractMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbConfigContract) EXPECT() *MockDbConfigContractMockRecorder {
	return m.recorder
}

// GetDatabase mocks base method.
func (m *MockDbConfigContract) GetDatabase() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDatabase")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDatabase indicates an expected call of GetDatabase.
func (mr *MockDbConfigContractMockRecorder) GetDatabase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabase", reflect.TypeOf((*MockDbConfigContract)(nil).GetDatabase))
}

// GetHost mocks base method.
func (m *MockDbConfigContract) GetHost() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHost")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHost indicates an expected call of GetHost.
func (mr *MockDbConfigContractMockRecorder) GetHost() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHost", reflect.TypeOf((*MockDbConfigContract)(nil).GetHost))
}

// GetPassword mocks base method.
func (m *MockDbConfigContract) GetPassword() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockDbConfigContractMockRecorder) GetPassword() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockDbConfigContract)(nil).GetPassword))
}

// GetPort mocks base method.
func (m *MockDbConfigContract) GetPort() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPort")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPort indicates an expected call of GetPort.
func (mr *MockDbConfigContractMockRecorder) GetPort() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPort", reflect.TypeOf((*MockDbConfigContract)(nil).GetPort))
}

// GetUser mocks base method.
func (m *MockDbConfigContract) GetUser() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUser indicates an expected call of GetUser.
func (mr *MockDbConfigContractMockRecorder) GetUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockDbConfigContract)(nil).GetUser))
}
